### PR TITLE
Perfer gradle and add support for multi-branch testing. 

### PR DESCRIPTION
**Pull request by jakelandis**
Most of the code here is copied and pasted from other plugins, such as beats input.

### CODE REVIEW

**Review by guyboertje — APPROVED** [review]
LGTM

**Comment by jakelandis** [comment]
@guyboertje - i needed to make some more changes, mind taking another look ?

**Comment by guyboertje** [comment]
Additions - LGTM

**Comment by guyboertje** [comment]
Merging on @jakelandis behalf
Going to rebase PR 19 on top of this.

**Comment by jakelandis** [comment]
@guyboertje - thanks!

**Pull request merged**
