### PR TITLE
Update index.asciidoc

### PR DESCRIPTION
**Pull request by DanRoscigno**
I think the term for adding or replacing data is usually enrichment, not enhancement.

### CODE REVIEW

**Comment by acchen97** [comment]
@karenzone mind reviewing this? should be a quick one. :)

**Review by karenzone — APPROVED** [review]
LGTM

**Comment by jordansissel** [comment]
@DanRoscigno can you rebase this PR?

**Comment by karenzone** [comment]
Remaining changes picked up  in #41

**Pull request closed without merging**
